//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FploWannierConverter {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FploWannierConverter.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1  H
        ///2  He
        ///3  Li
        ///4  Be
        ///5  B
        ///6  C
        ///7  N
        ///8  O
        ///9  F
        ///10 Ne
        ///11 Na
        ///12 Mg
        ///13 Al
        ///14 Si
        ///15 P
        ///16 S
        ///17 Cl
        ///18 Ar
        ///19 K
        ///20 Ca
        ///21 Sc
        ///22 Ti
        ///23 V
        ///24 Cr
        ///25 Mn
        ///26 Fe
        ///27 Co
        ///28 Ni
        ///29 Cu
        ///30 Zn
        ///31 Ga
        ///32 Ge
        ///33 As
        ///34 Se
        ///35 Br
        ///36 Kr
        ///37 Rb
        ///38 Sr
        ///39 Y
        ///40 Zr
        ///41 Nb
        ///42 Mo
        ///43 Tc
        ///44 Ru
        ///45 Rh
        ///46 Pd
        ///47 Ag
        ///48 Cd
        ///49 In
        ///50 Sn
        ///51 Sb
        ///52 Te
        ///53 I
        ///54 Xe
        ///55 Cs
        ///56 Ba
        ///57 La
        ///58 Ce
        ///59 Pr
        ///60 Nd
        ///61 Pm
        ///62 Sm
        ///63 Eu
        ///64 Gd
        ///65 Tb
        ///66 Dy
        ///67 Ho
        ///68 Er
        ///69 Tm
        ///70 Yb
        ///71 Lu
        ///72 Hf
        ///73 Ta
        ///74 W
        ///75 Re
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Atoms {
            get {
                return ResourceManager.GetString("Atoms", resourceCulture);
            }
        }
    }
}
