//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestMath {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TestMath.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matrix:
        ///2 2
        ///1, 0
        ///0, 1
        ///Eigenvalues:
        ///1
        ///1
        ///Eigenvectors:
        ///0.70710678, 0.70710678
        ///0.70710678, -0.70710678
        ///Matrix:
        ///2 2
        ///1, 1,
        ///1, 1,
        ///Eigenvalues
        ///2
        ///0
        ///Eigenvectors
        ///0.70710678, 0.70710678
        ///0.70710678, -0.70710678
        ///Matrix:
        ///3 3
        ///4, 0, 0
        ///0, 2, 1
        ///0, 1, 2
        ///Eigenvalues
        ///3
        ///1
        ///4
        ///Eigenvectors
        ///0,  0,  1
        ///0.70710678, 0.70710678, 0
        ///0.70710678, -0.70710678, 0
        ///Matrix:
        ///3 3 
        ///1, 0, 0
        ///0, 1.03947, -0.19471
        ///0, -0.19471, 1.96053
        ///Eigenvalues:
        ///2
        ///1
        ///1
        ///Eigenvectors:
        ///0, 0, 1
        ///-0.198670, 0.980066, 0
        ///0.980066,  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Matrices {
            get {
                return ResourceManager.GetString("Matrices", resourceCulture);
            }
        }
    }
}
